/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TravelTagService } from "../travelTag.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TravelTagCreateInput } from "./TravelTagCreateInput";
import { TravelTag } from "./TravelTag";
import { TravelTagFindManyArgs } from "./TravelTagFindManyArgs";
import { TravelTagWhereUniqueInput } from "./TravelTagWhereUniqueInput";
import { TravelTagUpdateInput } from "./TravelTagUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TravelTagControllerBase {
  constructor(
    protected readonly service: TravelTagService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TravelTag })
  @nestAccessControl.UseRoles({
    resource: "TravelTag",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTravelTag(
    @common.Body() data: TravelTagCreateInput
  ): Promise<TravelTag> {
    return await this.service.createTravelTag({
      data: data,
      select: {
        description: true,
        id: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TravelTag] })
  @ApiNestedQuery(TravelTagFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TravelTag",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async travelTags(@common.Req() request: Request): Promise<TravelTag[]> {
    const args = plainToClass(TravelTagFindManyArgs, request.query);
    return this.service.travelTags({
      ...args,
      select: {
        description: true,
        id: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TravelTag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TravelTag",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async travelTag(
    @common.Param() params: TravelTagWhereUniqueInput
  ): Promise<TravelTag | null> {
    const result = await this.service.travelTag({
      where: params,
      select: {
        description: true,
        id: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TravelTag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TravelTag",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTravelTag(
    @common.Param() params: TravelTagWhereUniqueInput,
    @common.Body() data: TravelTagUpdateInput
  ): Promise<TravelTag | null> {
    try {
      return await this.service.updateTravelTag({
        where: params,
        data: data,
        select: {
          description: true,
          id: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TravelTag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TravelTag",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTravelTag(
    @common.Param() params: TravelTagWhereUniqueInput
  ): Promise<TravelTag | null> {
    try {
      return await this.service.deleteTravelTag({
        where: params,
        select: {
          description: true,
          id: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
