/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Travel } from "./Travel";
import { TravelCountArgs } from "./TravelCountArgs";
import { TravelFindManyArgs } from "./TravelFindManyArgs";
import { TravelFindUniqueArgs } from "./TravelFindUniqueArgs";
import { CreateTravelArgs } from "./CreateTravelArgs";
import { UpdateTravelArgs } from "./UpdateTravelArgs";
import { DeleteTravelArgs } from "./DeleteTravelArgs";
import { ActivityFindManyArgs } from "../../activity/base/ActivityFindManyArgs";
import { Activity } from "../../activity/base/Activity";
import { User } from "../../user/base/User";
import { TravelService } from "../travel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Travel)
export class TravelResolverBase {
  constructor(
    protected readonly service: TravelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Travel",
    action: "read",
    possession: "any",
  })
  async _travelsMeta(
    @graphql.Args() args: TravelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Travel])
  @nestAccessControl.UseRoles({
    resource: "Travel",
    action: "read",
    possession: "any",
  })
  async travels(@graphql.Args() args: TravelFindManyArgs): Promise<Travel[]> {
    return this.service.travels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Travel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Travel",
    action: "read",
    possession: "own",
  })
  async travel(
    @graphql.Args() args: TravelFindUniqueArgs
  ): Promise<Travel | null> {
    const result = await this.service.travel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Travel)
  @nestAccessControl.UseRoles({
    resource: "Travel",
    action: "create",
    possession: "any",
  })
  async createTravel(@graphql.Args() args: CreateTravelArgs): Promise<Travel> {
    return await this.service.createTravel({
      ...args,
      data: {
        ...args.data,

        createdby: {
          connect: args.data.createdby,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Travel)
  @nestAccessControl.UseRoles({
    resource: "Travel",
    action: "update",
    possession: "any",
  })
  async updateTravel(
    @graphql.Args() args: UpdateTravelArgs
  ): Promise<Travel | null> {
    try {
      return await this.service.updateTravel({
        ...args,
        data: {
          ...args.data,

          createdby: {
            connect: args.data.createdby,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Travel)
  @nestAccessControl.UseRoles({
    resource: "Travel",
    action: "delete",
    possession: "any",
  })
  async deleteTravel(
    @graphql.Args() args: DeleteTravelArgs
  ): Promise<Travel | null> {
    try {
      return await this.service.deleteTravel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Activity], { name: "activity" })
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "read",
    possession: "any",
  })
  async findActivity(
    @graphql.Parent() parent: Travel,
    @graphql.Args() args: ActivityFindManyArgs
  ): Promise<Activity[]> {
    const results = await this.service.findActivity(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "createdby",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getCreatedby(@graphql.Parent() parent: Travel): Promise<User | null> {
    const result = await this.service.getCreatedby(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
